# Generated by Django 4.2 on 2023-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groups_messages_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='reciever',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
