# Generated by Django 4.2 on 2023-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messages_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_images/default_img.png', null=True, upload_to='images/profile_images'),
        ),
    ]
