# Generated by Django 4.2 on 2023-07-06 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('last_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messages')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
