# Generated by Django 4.2 on 2023-07-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_recentmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentmsg',
            name='last_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.messages'),
        ),
    ]
